spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/err
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jackson:
    time-zone: America/Sao_Paulo
logging:
  level:
    ROOT: INFO

server:
  port: 8080
